name: Daily Bhakti Quote

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai

      - name: Generate quote
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_quote.py

      - name: Commit and push
        run: |
          git config user.name "HarshvardhanBot"
          git config user.email "bot@example.com"
          git add quote.json
          git commit -m "🕉️ Daily Bhakti Quote Update" || echo "No changes"
          git push
